### ISSUE TITLE
Final cleanup may be needed after default branch renaming to 'main'

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/glTF-Generator-Registry#4]
@donmccurdy @khronos2 I'm not sure exactly how this repository is wired into khronos.org infrastructure, other than links to it from other glTF pages / repositories. Now that the repository default branch has been renamed to 'main', if there are any automatic updates pulled into parts of khronos.org, they should be modified to pull from 'main' branch. I don't think that's true for this repository but I'm not certain. If people are just expected to view this on github, then nothing more needs be done and this can be closed.

**Comment by donmccurdy** [comment]
Thanks @oddhack! I'm not aware that any Khronos infra depends on this registry. I am using it in my viewer with a simple `curl`, which I'll update:

https://github.com/donmccurdy/three-gltf-viewer/blob/f293273c135b803ac9ca4a41c8ccf40cfb86003d/package.json#L28

This allows the viewer to suggest where to report bugs on glTF models created by various tools.
